language: php
php: ["7.4"]
sudo: false
dist: trusty

install:
- "wget -O - https://poggit.pmmp.io/res/travisInstall.sh | bash -s - || true"

script:
- "if [ -f ${TRAVIS_BUILD_DIR}/../PocketMine/unstaged/PlayerBar.phar ] ; then wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - PlayerBar PlayerBar ; else true ; fi"
